language: java
jdk:
- oraclejdk8

before_install:
  - sudo apt-get install jq
  - curl -o ~/codacy-coverage-reporter "$(curl https://circleci.com/api/v1.1/project/github/codacy/codacy-coverage-reporter/latest/artifacts | jq -r .[0].url)"
  - "export DISPLAY=:99.0"
  - "export TERM=dumb"
  - "sh -e /etc/init.d/xvfb start"
install: mvn install -DskipTests -Dgpg.skip
script: mvn -B verify
after_success: java -cp ~/codacy-coverage-reporter report --language Java --coverage-report aggregate/target/site/jacoco-aggregate/jacoco.xml
