language: java
jdk:
- oraclejdk8

before_install:
  - sudo apt-get install jq
  - curl -L -o codacy-coverage-reporter "https://dl.bintray.com/codacy/Binaries/$(curl https://api.bintray.com/packages/codacy/Binaries/codacy-coverage-reporter/versions/_latest | jq -r .name)/codacy-coverage-reporter"
  - chmod u+x codacy-coverage-reporter
  - "export DISPLAY=:99.0"
  - "export TERM=dumb"
  - "sh -e /etc/init.d/xvfb start"
install: mvn install -DskipTests -Dgpg.skip
script: mvn -B verify
after_success: ./codacy-coverage-reporter report --language Java --coverage-report aggregate/target/site/jacoco-aggregate/jacoco.xml
